apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
      nodePort: 30087
      name: bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      nodePort: 30074
      name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: neo4j:4.0
          ports:
            - containerPort: 7474
            - containerPort: 7687
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /data
          env:
            - name: NEO4J_dbms_connector_bolt_advertised__address
              value: "localhost:30087"
      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pv-claim